repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
  
- repo: local
  hooks:
    - id: unittest-check
      name: unittest-check
      entry: python3 -m coverage run -m unittest discover
      args: ["-v", "-s", ".", "-p", "'*test*.py"]
      pass_filenames: false
      language: system
      'types': [python]
      stages: [commit]
    - id: unittest-coverage
      name: unittest-coverage
      entry: python3 -m coverage report --fail-under=70
      pass_filenames: false
      language: system
      stages: [commit]
